[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.26'
evm_version = "cancun"
optimizer_runs = 800
via_ir = true
ffi = true
fs_permissions = [
    { access="read", path= "./" },
    { access = "read-write", path = ".forge-snapshots/"}
]
remappings = [
    '@layerzerolabs/oapp-evm/=lib/devtools/packages/oapp-evm/',
    '@layerzerolabs/lz-evm-protocol-v2/=lib/layerzero-v2/packages/layerzero-v2/evm/protocol',
]
[rpc_endpoints]
sepolia_key = "${API_KEY_SEPOLIA}"
ethena_testnet = "https://testnet.rpc.ethena.fi"
sepolia_testnet ="${API_KEY_SEPOLIA}"
ble = "https://testnet.rpc.ethena.fi"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options